### PR TITLE
Add caption

### PR DESCRIPTION
**Pull request by ericnewkirk**
Adds `caption` and `caption.color` arguments to `withSpinner`. Captions are implemented as an additional [div](https://github.com/daattali/shinycssloaders/issues/28#issuecomment-846040037) below the one containing the spinner. Not supported for spinner type 1 because the animation for that spinner causes the caption to move up and down with the animation, which is really goofy looking. Honestly I think 'if you need a caption pick any spinner other than number 1' is fair.

[28](https://github.com/daattali/shinycssloaders/issues/28)
[68](https://github.com/daattali/shinycssloaders/issues/68)

### CODE REVIEW

**Comment by daattali** [comment]
Hi @ericnewkirk I apologize for taking so long to get to this, but I do like this PR! I prefer to only have a caption parameter without a colour parameter though, only because there is already a very long list of parameters and I don't want there to be too many. Would you mind updating your PR to remove the captioncolour parameter and also to merge with the latest code?

Thanks!

**Comment by ericnewkirk** [comment]
@daattali sure, here you go. I also bumped the version number and added a bullet to NEWS.md, hope that's alright.

**Comment by daattali** [comment]
Thanks! I ended up adding another feature that was highly requested, so I'll see if the latest changes I made cause any issues with your new code :)

**Comment by ericnewkirk** [comment]
Haha, I took a stab at the show/hide feature too. [My approach](https://github.com/ericnewkirk/shinycssloaders/commit/bca33e7468bea15e4f96c783873c69069921be77) if you're interested.

**Comment by daattali** [comment]
Thanks, I took a look -- I do prefer a more minimal approach. Even if they both achieve the same result, I think this approach will be a bit harder to debug/understand/maintain. I always strive to have the code as simple and maintainable as possible.

**Review by daattali — CHANGES_REQUESTED** [review]
The caption tag should not be created if it's empty

**Comment by ericnewkirk** [comment]
I don't think the caption tag was being created if no caption was passed (former code):
```r
if (!is.null(caption) && type != 1)
          shiny::div(id = paste0(id, "_caption"), class = "shiny-spinner-custom", caption)
```

The PR needed to be updated anyway though given more recent changes, and I made an effort to streamline some things. See what you think. The `caption` object should be `NULL` [here](https://github.com/ericnewkirk/shinycssloaders/blob/master/R/buildSpinner.R#L135) if type 1 was specified or no caption was passed.

**Review by daattali — APPROVED** [review]

**Comment by daattali** [comment]
Thanks, I've done some extra work on this and will be merging it now.

**Pull request merged**
